export const c_account = {
  READ_SUCCESS: 'READ_ACCOUNT_SUCCESS',
  READ_FAILURE: 'READ_ACCOUNT_FAILURE',
}

export const c_message = {
  LIST_SUCCESS: 'LIST_MESSAGE_SUCCESS',
  LIST_FAILURE: 'LIST_MESSAGE_FAILURE',
  SENDING: 'SENDING_MESSAGE',
}
